version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_chat
      POSTGRES_USER: user_chat
      POSTGRES_PASSWORD: password_chat
    ports:
      - "5432:5432"

volumes:
  postgres_data:
